// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrQXXBLKVA-JVO5HSx0lZs7zB1R6AMVJk',
    appId: '1:541136620976:web:6d5c2d48e73fc4b03b1a75',
    messagingSenderId: '541136620976',
    projectId: 'lobosc-app-2026',
    authDomain: 'lobosc-app-2026.firebaseapp.com',
    storageBucket: 'lobosc-app-2026.firebasestorage.app',
    measurementId: 'G-5Z4V1P4G12',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDAxv6dmktQlhYT7THzgmrL0f4tkbKpW4',
    appId: '1:541136620976:android:34f11487c30f2d853b1a75',
    messagingSenderId: '541136620976',
    projectId: 'lobosc-app-2026',
    storageBucket: 'lobosc-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2GtgFj8Stw6oRza2ZfUJ0d4Z3B1z0sRE',
    appId: '1:541136620976:ios:dc32db1bde74eaa43b1a75',
    messagingSenderId: '541136620976',
    projectId: 'lobosc-app-2026',
    storageBucket: 'lobosc-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.appLb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2GtgFj8Stw6oRza2ZfUJ0d4Z3B1z0sRE',
    appId: '1:541136620976:ios:dc32db1bde74eaa43b1a75',
    messagingSenderId: '541136620976',
    projectId: 'lobosc-app-2026',
    storageBucket: 'lobosc-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.appLb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrQXXBLKVA-JVO5HSx0lZs7zB1R6AMVJk',
    appId: '1:541136620976:web:19f976baffc6d6323b1a75',
    messagingSenderId: '541136620976',
    projectId: 'lobosc-app-2026',
    authDomain: 'lobosc-app-2026.firebaseapp.com',
    storageBucket: 'lobosc-app-2026.firebasestorage.app',
    measurementId: 'G-QBS123G9HX',
  );
}
